"""empty message

Revision ID: f9773d2fec
Revises: None
Create Date: 2015-05-09 20:54:10.695103

"""

# revision identifiers, used by Alembic.
revision = 'f9773d2fec'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
